CREATE TABLE stock
(
    id INT NOT NULL AUTO_INCREMENT,
    value INT NOT NULL,
    PRIMARY KEY(id)
);

INSERT INTO stock VALUES(1, 100);
INSERT INTO stock VALUES(2, 50);
INSERT INTO stock VALUES(3, 0);